version: '3.8'
services:
  djangox-mysql:
    image: mysql:8.0
    container_name: djangox-mysql
    privileged: true
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: "djangox"
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    env_file:
      - ./configs/.env
    volumes:
      - "./docker_env/mysql/data:/var/lib/mysql"
      - "./docker_env/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker_env/mysql/logs:/logs"
    networks:
      app_net:
        ipv4_address: 13.0.0.13

  djangox-redis:
    image: redis:7.4.0-alpine
    container_name: djangox-redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./docker_env/redis/data:/data
      - ./docker_env/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    env_file:
      - ./configs/.env
    sysctls:
      - net.core.somaxconn=1024
    command: /bin/sh -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf && redis-server /etc/redis/redis.conf --appendonly yes --requirepass ${REDIS_PASSWORD}"
    privileged: true
    networks:
      app_net:
        ipv4_address: 13.0.0.14

  djangox-server:
    build:
      context: .
      dockerfile: ./docker_env/django/Dockerfile
    container_name: djangox-server
    working_dir: /app
    depends_on:
      - djangox-mysql
      - djangox-redis
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_HOST: djangox-mysql
      REDIS_HOST: djangox-redis
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: Asia/Shanghai
    env_file:
      - ./configs/.env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always
    networks:
      app_net:
        ipv4_address: 13.0.0.15

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 13.0.0.0/8